/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'SurfaceDialFilter.sys'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _UNICODE_STRING;
struct _DEVICE_OBJECT;
struct _DRIVER_OBJECT;
struct _DRIVER_EXTENSION;
struct _FAST_IO_DISPATCH;
struct _FILE_OBJECT;
struct _VPB;
struct _SECTION_OBJECT_POINTERS;
struct _IO_COMPLETION_CONTEXT;
struct _FILE_BASIC_INFORMATION;
struct _FILE_STANDARD_INFORMATION;
struct _FILE_NETWORK_OPEN_INFORMATION;
struct _ERESOURCE;
struct _OWNER_ENTRY;
struct _MDL;
struct _COMPRESSED_DATA_INFO;
struct _IRP;
struct _IO_STACK_LOCATION;
struct _IO_SECURITY_CONTEXT;
struct _SECURITY_QUALITY_OF_SERVICE;
struct _ACCESS_STATE;
struct _NAMED_PIPE_CREATE_PARAMETERS;
struct _MAILSLOT_CREATE_PARAMETERS;
struct _SCSI_REQUEST_BLOCK;
struct _FILE_GET_QUOTA_INFORMATION;
struct _INTERFACE;
struct _DEVICE_CAPABILITIES;
struct _IO_RESOURCE_REQUIREMENTS_LIST;
struct _POWER_SEQUENCE;
struct _CM_RESOURCE_LIST;
struct _KDPC;
struct _DEVOBJ_EXTENSION;

/* 1 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 2 */
typedef struct _GUID GUID;

/* 3 */
struct RUNTIME_FUNCTION
{
  void *__ptr32 FunctionStart;
  void *__ptr32 FunctionEnd;
  void *__ptr32 UnwindInfo;
};

/* 4 */
struct UNWIND_INFO_HDR
{
  char Ver3_Flags;
  char PrologSize;
  char CntUnwindCodes;
  char FrReg_FrRegOff;
};

/* 5 */
struct UNWIND_CODE
{
  char PrologOff;
  char OpCode_OpInfo;
};

/* 7 */
typedef unsigned int ULONG;

/* 8 */
typedef void *HANDLE;

/* 9 */
typedef struct _UNICODE_STRING *PUNICODE_STRING;

/* 15 */
typedef void *PVOID;

/* 6 */
struct _OBJECT_ATTRIBUTES
{
  ULONG Length;
  HANDLE RootDirectory;
  PUNICODE_STRING ObjectName;
  ULONG Attributes;
  PVOID SecurityDescriptor;
  PVOID SecurityQualityOfService;
};

/* 11 */
typedef unsigned __int16 USHORT;

/* 14 */
typedef unsigned __int16 wchar_t;

/* 13 */
typedef wchar_t WCHAR;

/* 12 */
typedef WCHAR *PWSTR;

/* 10 */
struct _UNICODE_STRING
{
  USHORT Length;
  USHORT MaximumLength;
  PWSTR Buffer;
};

/* 18 */
typedef unsigned int DWORD;

/* 19 */
typedef int LONG;

/* 17 */
struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E
{
  DWORD LowPart;
  LONG HighPart;
};

/* 20 */
typedef __int64 LONGLONG;

/* 16 */
union _LARGE_INTEGER
{
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  };
  struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E u;
  LONGLONG QuadPart;
};

/* 22 */
typedef USHORT USAGE;

/* 23 */
typedef unsigned __int8 UCHAR;

/* 24 */
typedef unsigned __int8 BOOLEAN;

/* 26 */
#pragma pack(push, 4)
struct _HIDP_VALUE_CAPS::$D10B5F657B465D66794202428CB38B41::$83D0A1D806B42BB3CFEB24AD25988CD4
{
  USAGE UsageMin;
  USAGE UsageMax;
  USHORT StringMin;
  USHORT StringMax;
  USHORT DesignatorMin;
  USHORT DesignatorMax;
  USHORT DataIndexMin;
  USHORT DataIndexMax;
};
#pragma pack(pop)

/* 27 */
#pragma pack(push, 4)
struct _HIDP_VALUE_CAPS::$D10B5F657B465D66794202428CB38B41::$9A2DEDAE27CA526CD6B2E1277E119468
{
  USAGE Usage;
  USAGE Reserved1;
  USHORT StringIndex;
  USHORT Reserved2;
  USHORT DesignatorIndex;
  USHORT Reserved3;
  USHORT DataIndex;
  USHORT Reserved4;
};
#pragma pack(pop)

/* 25 */
#pragma pack(push, 4)
union _HIDP_VALUE_CAPS::$D10B5F657B465D66794202428CB38B41
{
  struct _HIDP_VALUE_CAPS::$D10B5F657B465D66794202428CB38B41::$83D0A1D806B42BB3CFEB24AD25988CD4 Range;
  struct _HIDP_VALUE_CAPS::$D10B5F657B465D66794202428CB38B41::$9A2DEDAE27CA526CD6B2E1277E119468 NotRange;
};
#pragma pack(pop)

/* 21 */
#pragma pack(push, 4)
struct _HIDP_VALUE_CAPS
{
  USAGE UsagePage;
  UCHAR ReportID;
  BOOLEAN IsAlias;
  USHORT BitField;
  USHORT LinkCollection;
  USAGE LinkUsage;
  USAGE LinkUsagePage;
  BOOLEAN IsRange;
  BOOLEAN IsStringRange;
  BOOLEAN IsDesignatorRange;
  BOOLEAN IsAbsolute;
  BOOLEAN HasNull;
  UCHAR Reserved;
  USHORT BitSize;
  USHORT ReportCount;
  USHORT Reserved2[5];
  ULONG UnitsExp;
  ULONG Units;
  LONG LogicalMin;
  LONG LogicalMax;
  LONG PhysicalMin;
  LONG PhysicalMax;
  #pragma pack(push, 4)
  union
  {
    struct _HIDP_VALUE_CAPS::$D10B5F657B465D66794202428CB38B41::$83D0A1D806B42BB3CFEB24AD25988CD4 Range;
    struct _HIDP_VALUE_CAPS::$D10B5F657B465D66794202428CB38B41::$9A2DEDAE27CA526CD6B2E1277E119468 NotRange;
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 29 */
typedef __int16 CSHORT;

/* 358 */
typedef struct _IO_TIMER *PIO_TIMER;

/* 43 */
typedef struct _VPB *PVPB;

/* 153 */
typedef char CCHAR;

/* 74 */
struct _LIST_ENTRY
{
  struct _LIST_ENTRY *Flink;
  struct _LIST_ENTRY *Blink;
};

/* 73 */
typedef struct _LIST_ENTRY LIST_ENTRY;

/* 167 */
struct _KDEVICE_QUEUE_ENTRY
{
  LIST_ENTRY DeviceListEntry;
  ULONG SortKey;
  BOOLEAN Inserted;
};

/* 166 */
typedef struct _KDEVICE_QUEUE_ENTRY KDEVICE_QUEUE_ENTRY;

/* 363 */
struct _WAIT_CONTEXT_BLOCK::$25036D26EC3128001C844A9BD42D8664::$F03CBEE8C81F93D549DFD49A4693D244
{
  LIST_ENTRY DmaWaitEntry;
  ULONG NumberOfChannels;
  unsigned __int32 SyncCallback : 1;
  unsigned __int32 DmaContext : 1;
  unsigned __int32 ZeroMapRegisters : 1;
  unsigned __int32 Reserved : 9;
  unsigned __int32 NumberOfRemapPages : 20;
};

/* 362 */
union _WAIT_CONTEXT_BLOCK::$25036D26EC3128001C844A9BD42D8664
{
  KDEVICE_QUEUE_ENTRY WaitQueueEntry;
  struct
  {
    LIST_ENTRY DmaWaitEntry;
    ULONG NumberOfChannels;
    unsigned __int32 SyncCallback : 1;
    unsigned __int32 DmaContext : 1;
    unsigned __int32 ZeroMapRegisters : 1;
    unsigned __int32 Reserved : 9;
    unsigned __int32 NumberOfRemapPages : 20;
  };
};

/* 367 */
enum _IO_ALLOCATION_ACTION
{
  KeepObject = 0x1,
  DeallocateObject = 0x2,
  DeallocateObjectKeepRegisters = 0x3,
};

/* 366 */
typedef enum _IO_ALLOCATION_ACTION IO_ALLOCATION_ACTION;

/* 365 */
typedef IO_ALLOCATION_ACTION __stdcall DRIVER_CONTROL(struct _DEVICE_OBJECT *DeviceObject, struct _IRP *Irp, PVOID MapRegisterBase, PVOID Context);

/* 364 */
typedef DRIVER_CONTROL *PDRIVER_CONTROL;

/* 368 */
typedef struct _KDPC *PKDPC;

/* 361 */
struct _WAIT_CONTEXT_BLOCK
{
  union
  {
    KDEVICE_QUEUE_ENTRY WaitQueueEntry;
    struct
    {
      LIST_ENTRY DmaWaitEntry;
      ULONG NumberOfChannels;
      unsigned __int32 SyncCallback : 1;
      unsigned __int32 DmaContext : 1;
      unsigned __int32 ZeroMapRegisters : 1;
      unsigned __int32 Reserved : 9;
      unsigned __int32 NumberOfRemapPages : 20;
    };
  };
  PDRIVER_CONTROL DeviceRoutine;
  PVOID DeviceContext;
  ULONG NumberOfMapRegisters;
  PVOID DeviceObject;
  PVOID CurrentIrp;
  PKDPC BufferChainingDpc;
};

/* 360 */
typedef struct _WAIT_CONTEXT_BLOCK WAIT_CONTEXT_BLOCK;

/* 359 */
union _DEVICE_OBJECT::$3ABEFC84562B0417329DFE2AD83813CB
{
  LIST_ENTRY ListEntry;
  WAIT_CONTEXT_BLOCK Wcb;
};

/* 78 */
typedef unsigned __int64 ULONG_PTR;

/* 77 */
typedef ULONG_PTR KSPIN_LOCK;

/* 379 */
struct _KDEVICE_QUEUE::$9FAF936D47973D5FBAA72DAF24011AE0::$18E3EACC1E717291AA7C720ECCD5C45C
{
  __int64 Reserved : 8;
  __int64 Hint : 56;
};

/* 378 */
union _KDEVICE_QUEUE::$9FAF936D47973D5FBAA72DAF24011AE0
{
  BOOLEAN Busy;
  struct
  {
    __int64 Reserved : 8;
    __int64 Hint : 56;
  };
};

/* 377 */
struct _KDEVICE_QUEUE
{
  CSHORT Type;
  CSHORT Size;
  LIST_ENTRY DeviceListHead;
  KSPIN_LOCK Lock;
  union
  {
    BOOLEAN Busy;
    struct
    {
      __int64 Reserved : 8;
      __int64 Hint : 56;
    };
  };
};

/* 376 */
typedef struct _KDEVICE_QUEUE KDEVICE_QUEUE;

/* 371 */
struct _KDPC::$6963FFE55BC4627E7AE37E9650A61BA0::$11C356C5F0E6BDA2274B3634F305E8EF
{
  UCHAR Type;
  UCHAR Importance;
  volatile USHORT Number;
};

/* 370 */
union _KDPC::$6963FFE55BC4627E7AE37E9650A61BA0
{
  ULONG TargetInfoAsUlong;
  struct
  {
    UCHAR Type;
    UCHAR Importance;
    volatile USHORT Number;
  };
};

/* 373 */
struct _SINGLE_LIST_ENTRY
{
  struct _SINGLE_LIST_ENTRY *Next;
};

/* 372 */
typedef struct _SINGLE_LIST_ENTRY SINGLE_LIST_ENTRY;

/* 274 */
typedef ULONG_PTR KAFFINITY;

/* 375 */
typedef void __stdcall KDEFERRED_ROUTINE(struct _KDPC *Dpc, PVOID DeferredContext, PVOID SystemArgument1, PVOID SystemArgument2);

/* 374 */
typedef KDEFERRED_ROUTINE *PKDEFERRED_ROUTINE;

/* 369 */
struct _KDPC
{
  union
  {
    ULONG TargetInfoAsUlong;
    struct
    {
      UCHAR Type;
      UCHAR Importance;
      volatile USHORT Number;
    };
  };
  SINGLE_LIST_ENTRY DpcListEntry;
  KAFFINITY ProcessorHistory;
  PKDEFERRED_ROUTINE DeferredRoutine;
  PVOID DeferredContext;
  PVOID SystemArgument1;
  PVOID SystemArgument2;
  PVOID DpcData;
};

/* 380 */
typedef struct _KDPC KDPC;

/* 191 */
typedef PVOID PSECURITY_DESCRIPTOR;

/* 54 */
union _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$D43038B1DD00167268319662DF7D50CE
{
  volatile LONG Lock;
  LONG LockNV;
};

/* 55 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$147445C0E4E68EEE8CC57231FACAF18E
{
  UCHAR Type;
  UCHAR Signalling;
  UCHAR Size;
  UCHAR Reserved1;
};

/* 58 */
struct _DISPATCHER_HEADER::$::$::$C455783609593A5FC0070ED780464C2D::$F32BA6C812E0F769F09938C2098D009F
{
  unsigned __int8 Absolute : 1;
  unsigned __int8 Wake : 1;
  unsigned __int8 EncodedTolerableDelay : 6;
};

/* 57 */
union _DISPATCHER_HEADER::$::$C40575DFC387C8F4117E2F825EAF6417::$C455783609593A5FC0070ED780464C2D
{
  UCHAR TimerControlFlags;
  struct
  {
    unsigned __int8 Absolute : 1;
    unsigned __int8 Wake : 1;
    unsigned __int8 EncodedTolerableDelay : 6;
  };
};

/* 60 */
struct _DISPATCHER_HEADER::$::$::$05D45FD30F9D93B8752762EBBCB0BF0A::$AA905F972124AC55790449D6420AAEA5
{
  unsigned __int8 Index : 6;
  unsigned __int8 Inserted : 1;
  unsigned __int8 Expired : 1;
};

/* 59 */
union _DISPATCHER_HEADER::$::$C40575DFC387C8F4117E2F825EAF6417::$05D45FD30F9D93B8752762EBBCB0BF0A
{
  UCHAR TimerMiscFlags;
  struct
  {
    unsigned __int8 Index : 6;
    unsigned __int8 Inserted : 1;
    unsigned __int8 Expired : 1;
  };
};

/* 56 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$C40575DFC387C8F4117E2F825EAF6417
{
  UCHAR TimerType;
  union
  {
    UCHAR TimerControlFlags;
    struct
    {
      unsigned __int8 Absolute : 1;
      unsigned __int8 Wake : 1;
      unsigned __int8 EncodedTolerableDelay : 6;
    };
  };
  UCHAR Hand;
  union
  {
    UCHAR TimerMiscFlags;
    struct
    {
      unsigned __int8 Index : 6;
      unsigned __int8 Inserted : 1;
      unsigned __int8 Expired : 1;
    };
  };
};

/* 63 */
struct _DISPATCHER_HEADER::$::$::$BC95C1005138DD6C54C311F6EA5D109E::$79EE8220B9CBCC15640D116F9688A663
{
  unsigned __int8 Timer2Inserted : 1;
  unsigned __int8 Timer2Expiring : 1;
  unsigned __int8 Timer2CancelPending : 1;
  unsigned __int8 Timer2SetPending : 1;
  unsigned __int8 Timer2Running : 1;
  unsigned __int8 Timer2Disabled : 1;
  unsigned __int8 Timer2ReservedFlags : 2;
};

/* 62 */
union _DISPATCHER_HEADER::$::$93871522DA2DA651F6EE6945327295BD::$BC95C1005138DD6C54C311F6EA5D109E
{
  UCHAR Timer2Flags;
  struct
  {
    unsigned __int8 Timer2Inserted : 1;
    unsigned __int8 Timer2Expiring : 1;
    unsigned __int8 Timer2CancelPending : 1;
    unsigned __int8 Timer2SetPending : 1;
    unsigned __int8 Timer2Running : 1;
    unsigned __int8 Timer2Disabled : 1;
    unsigned __int8 Timer2ReservedFlags : 2;
  };
};

/* 61 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$93871522DA2DA651F6EE6945327295BD
{
  UCHAR Timer2Type;
  union
  {
    UCHAR Timer2Flags;
    struct
    {
      unsigned __int8 Timer2Inserted : 1;
      unsigned __int8 Timer2Expiring : 1;
      unsigned __int8 Timer2CancelPending : 1;
      unsigned __int8 Timer2SetPending : 1;
      unsigned __int8 Timer2Running : 1;
      unsigned __int8 Timer2Disabled : 1;
      unsigned __int8 Timer2ReservedFlags : 2;
    };
  };
  UCHAR Timer2ComponentId;
  UCHAR Timer2RelativeId;
};

/* 66 */
struct _DISPATCHER_HEADER::$::$::$1728BC3AACECDC2141D1E32FE66EA23E::$3EFE0FF07DD77BBDEABCDA7FF0A75165
{
  unsigned __int8 Abandoned : 1;
  unsigned __int8 DisableIncrement : 1;
  unsigned __int8 QueueReservedControlFlags : 6;
};

/* 65 */
union _DISPATCHER_HEADER::$::$5BEE508906071BCCD40638FEAF58F305::$1728BC3AACECDC2141D1E32FE66EA23E
{
  UCHAR QueueControlFlags;
  struct
  {
    unsigned __int8 Abandoned : 1;
    unsigned __int8 DisableIncrement : 1;
    unsigned __int8 QueueReservedControlFlags : 6;
  };
};

/* 64 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$5BEE508906071BCCD40638FEAF58F305
{
  UCHAR QueueType;
  union
  {
    UCHAR QueueControlFlags;
    struct
    {
      unsigned __int8 Abandoned : 1;
      unsigned __int8 DisableIncrement : 1;
      unsigned __int8 QueueReservedControlFlags : 6;
    };
  };
  UCHAR QueueSize;
  UCHAR QueueReserved;
};

/* 69 */
struct _DISPATCHER_HEADER::$::$::$0E76FCEEB5609B75E7D96C8D89B50E90::$289C34DDD4E6D8A579D3E1CDF74CD890
{
  unsigned __int8 CycleProfiling : 1;
  unsigned __int8 CounterProfiling : 1;
  unsigned __int8 GroupScheduling : 1;
  unsigned __int8 AffinitySet : 1;
  unsigned __int8 Tagged : 1;
  unsigned __int8 EnergyProfiling : 1;
  unsigned __int8 SchedulerAssist : 1;
  unsigned __int8 ThreadReservedControlFlags : 1;
};

/* 68 */
union _DISPATCHER_HEADER::$::$C4D4F6505347955A7E49BDD08F2B07A4::$0E76FCEEB5609B75E7D96C8D89B50E90
{
  UCHAR ThreadControlFlags;
  struct
  {
    unsigned __int8 CycleProfiling : 1;
    unsigned __int8 CounterProfiling : 1;
    unsigned __int8 GroupScheduling : 1;
    unsigned __int8 AffinitySet : 1;
    unsigned __int8 Tagged : 1;
    unsigned __int8 EnergyProfiling : 1;
    unsigned __int8 SchedulerAssist : 1;
    unsigned __int8 ThreadReservedControlFlags : 1;
  };
};

/* 71 */
struct _DISPATCHER_HEADER::$::$::$49B2F56B82B650C36577DFA53D44488C::$5B46111089229E54AB036CC97FD77231
{
  unsigned __int8 ActiveDR7 : 1;
  unsigned __int8 Instrumented : 1;
  unsigned __int8 Minimal : 1;
  unsigned __int8 Reserved4 : 3;
  unsigned __int8 UmsScheduled : 1;
  unsigned __int8 UmsPrimary : 1;
};

/* 70 */
union _DISPATCHER_HEADER::$::$C4D4F6505347955A7E49BDD08F2B07A4::$49B2F56B82B650C36577DFA53D44488C
{
  UCHAR DebugActive;
  struct
  {
    unsigned __int8 ActiveDR7 : 1;
    unsigned __int8 Instrumented : 1;
    unsigned __int8 Minimal : 1;
    unsigned __int8 Reserved4 : 3;
    unsigned __int8 UmsScheduled : 1;
    unsigned __int8 UmsPrimary : 1;
  };
};

/* 67 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$C4D4F6505347955A7E49BDD08F2B07A4
{
  UCHAR ThreadType;
  UCHAR ThreadReserved;
  union
  {
    UCHAR ThreadControlFlags;
    struct
    {
      unsigned __int8 CycleProfiling : 1;
      unsigned __int8 CounterProfiling : 1;
      unsigned __int8 GroupScheduling : 1;
      unsigned __int8 AffinitySet : 1;
      unsigned __int8 Tagged : 1;
      unsigned __int8 EnergyProfiling : 1;
      unsigned __int8 SchedulerAssist : 1;
      unsigned __int8 ThreadReservedControlFlags : 1;
    };
  };
  union
  {
    UCHAR DebugActive;
    struct
    {
      unsigned __int8 ActiveDR7 : 1;
      unsigned __int8 Instrumented : 1;
      unsigned __int8 Minimal : 1;
      unsigned __int8 Reserved4 : 3;
      unsigned __int8 UmsScheduled : 1;
      unsigned __int8 UmsPrimary : 1;
    };
  };
};

/* 72 */
struct _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217::$3EF41BFA0BF183FFCD9D039EF3AA2B7F
{
  UCHAR MutantType;
  UCHAR MutantSize;
  BOOLEAN DpcActive;
  UCHAR MutantReserved;
};

/* 53 */
union _DISPATCHER_HEADER::$C692E9AEA376E54441FB800CD9AFB217
{
  union
  {
    volatile LONG Lock;
    LONG LockNV;
  };
  struct
  {
    UCHAR Type;
    UCHAR Signalling;
    UCHAR Size;
    UCHAR Reserved1;
  };
  struct
  {
    UCHAR TimerType;
    union
    {
      UCHAR TimerControlFlags;
      struct
      {
        unsigned __int8 Absolute : 1;
        unsigned __int8 Wake : 1;
        unsigned __int8 EncodedTolerableDelay : 6;
      };
    };
    UCHAR Hand;
    union
    {
      UCHAR TimerMiscFlags;
      struct
      {
        unsigned __int8 Index : 6;
        unsigned __int8 Inserted : 1;
        unsigned __int8 Expired : 1;
      };
    };
  };
  struct
  {
    UCHAR Timer2Type;
    union
    {
      UCHAR Timer2Flags;
      struct
      {
        unsigned __int8 Timer2Inserted : 1;
        unsigned __int8 Timer2Expiring : 1;
        unsigned __int8 Timer2CancelPending : 1;
        unsigned __int8 Timer2SetPending : 1;
        unsigned __int8 Timer2Running : 1;
        unsigned __int8 Timer2Disabled : 1;
        unsigned __int8 Timer2ReservedFlags : 2;
      };
    };
    UCHAR Timer2ComponentId;
    UCHAR Timer2RelativeId;
  };
  struct
  {
    UCHAR QueueType;
    union
    {
      UCHAR QueueControlFlags;
      struct
      {
        unsigned __int8 Abandoned : 1;
        unsigned __int8 DisableIncrement : 1;
        unsigned __int8 QueueReservedControlFlags : 6;
      };
    };
    UCHAR QueueSize;
    UCHAR QueueReserved;
  };
  struct
  {
    UCHAR ThreadType;
    UCHAR ThreadReserved;
    union
    {
      UCHAR ThreadControlFlags;
      struct
      {
        unsigned __int8 CycleProfiling : 1;
        unsigned __int8 CounterProfiling : 1;
        unsigned __int8 GroupScheduling : 1;
        unsigned __int8 AffinitySet : 1;
        unsigned __int8 Tagged : 1;
        unsigned __int8 EnergyProfiling : 1;
        unsigned __int8 SchedulerAssist : 1;
        unsigned __int8 ThreadReservedControlFlags : 1;
      };
    };
    union
    {
      UCHAR DebugActive;
      struct
      {
        unsigned __int8 ActiveDR7 : 1;
        unsigned __int8 Instrumented : 1;
        unsigned __int8 Minimal : 1;
        unsigned __int8 Reserved4 : 3;
        unsigned __int8 UmsScheduled : 1;
        unsigned __int8 UmsPrimary : 1;
      };
    };
  };
  struct
  {
    UCHAR MutantType;
    UCHAR MutantSize;
    BOOLEAN DpcActive;
    UCHAR MutantReserved;
  };
};

/* 52 */
struct _DISPATCHER_HEADER
{
  union
  {
    union
    {
      volatile LONG Lock;
      LONG LockNV;
    };
    struct
    {
      UCHAR Type;
      UCHAR Signalling;
      UCHAR Size;
      UCHAR Reserved1;
    };
    struct
    {
      UCHAR TimerType;
      union
      {
        UCHAR TimerControlFlags;
        struct
        {
          unsigned __int8 Absolute : 1;
          unsigned __int8 Wake : 1;
          unsigned __int8 EncodedTolerableDelay : 6;
        };
      };
      UCHAR Hand;
      union
      {
        UCHAR TimerMiscFlags;
        struct
        {
          unsigned __int8 Index : 6;
          unsigned __int8 Inserted : 1;
          unsigned __int8 Expired : 1;
        };
      };
    };
    struct
    {
      UCHAR Timer2Type;
      union
      {
        UCHAR Timer2Flags;
        struct
        {
          unsigned __int8 Timer2Inserted : 1;
          unsigned __int8 Timer2Expiring : 1;
          unsigned __int8 Timer2CancelPending : 1;
          unsigned __int8 Timer2SetPending : 1;
          unsigned __int8 Timer2Running : 1;
          unsigned __int8 Timer2Disabled : 1;
          unsigned __int8 Timer2ReservedFlags : 2;
        };
      };
      UCHAR Timer2ComponentId;
      UCHAR Timer2RelativeId;
    };
    struct
    {
      UCHAR QueueType;
      union
      {
        UCHAR QueueControlFlags;
        struct
        {
          unsigned __int8 Abandoned : 1;
          unsigned __int8 DisableIncrement : 1;
          unsigned __int8 QueueReservedControlFlags : 6;
        };
      };
      UCHAR QueueSize;
      UCHAR QueueReserved;
    };
    struct
    {
      UCHAR ThreadType;
      UCHAR ThreadReserved;
      union
      {
        UCHAR ThreadControlFlags;
        struct
        {
          unsigned __int8 CycleProfiling : 1;
          unsigned __int8 CounterProfiling : 1;
          unsigned __int8 GroupScheduling : 1;
          unsigned __int8 AffinitySet : 1;
          unsigned __int8 Tagged : 1;
          unsigned __int8 EnergyProfiling : 1;
          unsigned __int8 SchedulerAssist : 1;
          unsigned __int8 ThreadReservedControlFlags : 1;
        };
      };
      union
      {
        UCHAR DebugActive;
        struct
        {
          unsigned __int8 ActiveDR7 : 1;
          unsigned __int8 Instrumented : 1;
          unsigned __int8 Minimal : 1;
          unsigned __int8 Reserved4 : 3;
          unsigned __int8 UmsScheduled : 1;
          unsigned __int8 UmsPrimary : 1;
        };
      };
    };
    struct
    {
      UCHAR MutantType;
      UCHAR MutantSize;
      BOOLEAN DpcActive;
      UCHAR MutantReserved;
    };
  };
  LONG SignalState;
  LIST_ENTRY WaitListHead;
};

/* 51 */
typedef struct _DISPATCHER_HEADER DISPATCHER_HEADER;

/* 50 */
struct _KEVENT
{
  DISPATCHER_HEADER Header;
};

/* 49 */
typedef struct _KEVENT KEVENT;

/* 28 */
struct __declspec(align(16)) _DEVICE_OBJECT
{
  CSHORT Type;
  USHORT Size;
  LONG ReferenceCount;
  struct _DRIVER_OBJECT *DriverObject;
  struct _DEVICE_OBJECT *NextDevice;
  struct _DEVICE_OBJECT *AttachedDevice;
  struct _IRP *CurrentIrp;
  PIO_TIMER Timer;
  ULONG Flags;
  ULONG Characteristics;
  PVPB Vpb;
  PVOID DeviceExtension;
  ULONG DeviceType;
  CCHAR StackSize;
  union _DEVICE_OBJECT::$3ABEFC84562B0417329DFE2AD83813CB Queue;
  ULONG AlignmentRequirement;
  KDEVICE_QUEUE DeviceQueue;
  KDPC Dpc;
  ULONG ActiveThreadCount;
  PSECURITY_DESCRIPTOR SecurityDescriptor;
  KEVENT DeviceLock;
  USHORT SectorSize;
  USHORT Spare1;
  struct _DEVOBJ_EXTENSION *DeviceObjectExtension;
  PVOID Reserved;
};

/* 31 */
typedef struct _DEVICE_OBJECT *PDEVICE_OBJECT;

/* 32 */
typedef struct _DRIVER_EXTENSION *PDRIVER_EXTENSION;

/* 37 */
typedef struct _UNICODE_STRING UNICODE_STRING;

/* 38 */
typedef struct _FAST_IO_DISPATCH *PFAST_IO_DISPATCH;

/* 36 */
typedef int NTSTATUS;

/* 351 */
typedef NTSTATUS __stdcall DRIVER_INITIALIZE(struct _DRIVER_OBJECT *DriverObject, PUNICODE_STRING RegistryPath);

/* 350 */
typedef DRIVER_INITIALIZE *PDRIVER_INITIALIZE;

/* 353 */
typedef void __stdcall DRIVER_STARTIO(struct _DEVICE_OBJECT *DeviceObject, struct _IRP *Irp);

/* 352 */
typedef DRIVER_STARTIO *PDRIVER_STARTIO;

/* 355 */
typedef void __stdcall DRIVER_UNLOAD(struct _DRIVER_OBJECT *DriverObject);

/* 354 */
typedef DRIVER_UNLOAD *PDRIVER_UNLOAD;

/* 357 */
typedef NTSTATUS __stdcall DRIVER_DISPATCH(struct _DEVICE_OBJECT *DeviceObject, struct _IRP *Irp);

/* 356 */
typedef DRIVER_DISPATCH *PDRIVER_DISPATCH;

/* 30 */
struct _DRIVER_OBJECT
{
  CSHORT Type;
  CSHORT Size;
  PDEVICE_OBJECT DeviceObject;
  ULONG Flags;
  PVOID DriverStart;
  ULONG DriverSize;
  PVOID DriverSection;
  PDRIVER_EXTENSION DriverExtension;
  UNICODE_STRING DriverName;
  PUNICODE_STRING HardwareDatabase;
  PFAST_IO_DISPATCH FastIoDispatch;
  PDRIVER_INITIALIZE DriverInit;
  PDRIVER_STARTIO DriverStartIo;
  PDRIVER_UNLOAD DriverUnload;
  PDRIVER_DISPATCH MajorFunction[28];
};

/* 130 */
typedef struct _MDL *PMDL;

/* 150 */
union _IRP::$CBBBB9F4F0755A16DC8A369061485BEC
{
  struct _IRP *MasterIrp;
  LONG IrpCount;
  PVOID SystemBuffer;
};

/* 82 */
union _IO_STATUS_BLOCK::$77CEE0AF02806C16F943E6B3BF8ECA77
{
  NTSTATUS Status;
  PVOID Pointer;
};

/* 81 */
struct _IO_STATUS_BLOCK
{
  union
  {
    NTSTATUS Status;
    PVOID Pointer;
  };
  ULONG_PTR Information;
};

/* 151 */
typedef struct _IO_STATUS_BLOCK IO_STATUS_BLOCK;

/* 152 */
typedef CCHAR KPROCESSOR_MODE;

/* 154 */
typedef char CHAR;

/* 155 */
typedef UCHAR KIRQL;

/* 80 */
typedef struct _IO_STATUS_BLOCK *PIO_STATUS_BLOCK;

/* 156 */
typedef struct _KEVENT *PKEVENT;

/* 160 */
typedef void (__stdcall *PIO_APC_ROUTINE)(PVOID ApcContext, PIO_STATUS_BLOCK IoStatusBlock, ULONG Reserved);

/* 159 */
union _IRP::$::$1DDC8106121C6C57578C3B7B583E783E::$72AAA2734763A5172362D9A41AF08CB4
{
  PIO_APC_ROUTINE UserApcRoutine;
  PVOID IssuingProcess;
};

/* 158 */
struct _IRP::$6B96A96ED958C92F2CB4B83EAB343043::$1DDC8106121C6C57578C3B7B583E783E
{
  union
  {
    PIO_APC_ROUTINE UserApcRoutine;
    PVOID IssuingProcess;
  };
  PVOID UserApcContext;
};

/* 48 */
typedef union _LARGE_INTEGER LARGE_INTEGER;

/* 157 */
union _IRP::$6B96A96ED958C92F2CB4B83EAB343043
{
  struct _IRP::$6B96A96ED958C92F2CB4B83EAB343043::$1DDC8106121C6C57578C3B7B583E783E AsynchronousParameters;
  LARGE_INTEGER AllocationSize;
};

/* 162 */
typedef void __stdcall DRIVER_CANCEL(struct _DEVICE_OBJECT *DeviceObject, struct _IRP *Irp);

/* 161 */
typedef DRIVER_CANCEL *PDRIVER_CANCEL;

/* 168 */
struct _IRP::$::$::$63BBF9CAFCFD23268916A053C4643290::$D67882FDDE0993B795A398485751D997
{
  PVOID DriverContext[4];
};

/* 165 */
union _IRP::$::$2AD798E65616C4F7304824DBFA27E419::$63BBF9CAFCFD23268916A053C4643290
{
  KDEVICE_QUEUE_ENTRY DeviceQueueEntry;
  struct
  {
    PVOID DriverContext[4];
  };
};

/* 169 */
typedef struct _KTHREAD *PETHREAD;

/* 170 */
typedef CHAR *PCHAR;

/* 172 */
union _IRP::$::$::$665C8370128C04AB892B069E6FB086E8::$8B5CD6CDFBAAB114E6B0B83ED2C2A4E9
{
  struct _IO_STACK_LOCATION *CurrentStackLocation;
  ULONG PacketType;
};

/* 171 */
struct _IRP::$::$2AD798E65616C4F7304824DBFA27E419::$665C8370128C04AB892B069E6FB086E8
{
  LIST_ENTRY ListEntry;
  union
  {
    struct _IO_STACK_LOCATION *CurrentStackLocation;
    ULONG PacketType;
  };
};

/* 215 */
typedef struct _FILE_OBJECT *PFILE_OBJECT;

/* 164 */
struct _IRP::$66699B8BF83DC91F51A70E4C6E3F33A6::$2AD798E65616C4F7304824DBFA27E419
{
  union
  {
    KDEVICE_QUEUE_ENTRY DeviceQueueEntry;
    struct
    {
      PVOID DriverContext[4];
    };
  };
  PETHREAD Thread;
  PCHAR AuxiliaryBuffer;
  struct
  {
    LIST_ENTRY ListEntry;
    union
    {
      struct _IO_STACK_LOCATION *CurrentStackLocation;
      ULONG PacketType;
    };
  };
  PFILE_OBJECT OriginalFileObject;
};

/* 342 */
struct _KAPC
{
  UCHAR Type;
  UCHAR SpareByte0;
  UCHAR Size;
  UCHAR SpareByte1;
  ULONG SpareLong0;
  struct _KTHREAD *Thread;
  LIST_ENTRY ApcListEntry;
  PVOID Reserved[3];
  PVOID NormalContext;
  PVOID SystemArgument1;
  PVOID SystemArgument2;
  CCHAR ApcStateIndex;
  KPROCESSOR_MODE ApcMode;
  BOOLEAN Inserted;
};

/* 341 */
typedef struct _KAPC KAPC;

/* 163 */
union _IRP::$66699B8BF83DC91F51A70E4C6E3F33A6
{
  struct _IRP::$66699B8BF83DC91F51A70E4C6E3F33A6::$2AD798E65616C4F7304824DBFA27E419 Overlay;
  KAPC Apc;
  PVOID CompletionKey;
};

/* 149 */
struct __declspec(align(16)) _IRP
{
  CSHORT Type;
  USHORT Size;
  PMDL MdlAddress;
  ULONG Flags;
  union _IRP::$CBBBB9F4F0755A16DC8A369061485BEC AssociatedIrp;
  LIST_ENTRY ThreadListEntry;
  IO_STATUS_BLOCK IoStatus;
  KPROCESSOR_MODE RequestorMode;
  BOOLEAN PendingReturned;
  CHAR StackCount;
  CHAR CurrentLocation;
  BOOLEAN Cancel;
  KIRQL CancelIrql;
  CCHAR ApcEnvironment;
  UCHAR AllocationFlags;
  PIO_STATUS_BLOCK UserIosb;
  PKEVENT UserEvent;
  union _IRP::$6B96A96ED958C92F2CB4B83EAB343043 Overlay;
  PDRIVER_CANCEL CancelRoutine;
  PVOID UserBuffer;
  union _IRP::$66699B8BF83DC91F51A70E4C6E3F33A6 Tail;
};

/* 44 */
struct _VPB
{
  CSHORT Type;
  CSHORT Size;
  USHORT Flags;
  USHORT VolumeLabelLength;
  struct _DEVICE_OBJECT *DeviceObject;
  struct _DEVICE_OBJECT *RealDevice;
  ULONG SerialNumber;
  ULONG ReferenceCount;
  WCHAR VolumeLabel[32];
};

/* 381 */
struct _DEVOBJ_EXTENSION
{
  CSHORT Type;
  USHORT Size;
  PDEVICE_OBJECT DeviceObject;
  ULONG PowerFlags;
  struct _DEVICE_OBJECT_POWER_EXTENSION *Dope;
  ULONG ExtensionFlags;
  PVOID DeviceNode;
  PDEVICE_OBJECT AttachedTo;
  LONG StartIoCount;
  LONG StartIoKey;
  ULONG StartIoFlags;
  PVPB Vpb;
  PVOID DependencyNode;
  PVOID InterruptContext;
  PVOID VerifierContext;
};

/* 35 */
typedef NTSTATUS __stdcall DRIVER_ADD_DEVICE(struct _DRIVER_OBJECT *DriverObject, struct _DEVICE_OBJECT *PhysicalDeviceObject);

/* 34 */
typedef DRIVER_ADD_DEVICE *PDRIVER_ADD_DEVICE;

/* 33 */
struct _DRIVER_EXTENSION
{
  struct _DRIVER_OBJECT *DriverObject;
  PDRIVER_ADD_DEVICE AddDevice;
  ULONG Count;
  UNICODE_STRING ServiceKeyName;
};

/* 79 */
typedef union _LARGE_INTEGER *PLARGE_INTEGER;

/* 41 */
typedef BOOLEAN __stdcall FAST_IO_CHECK_IF_POSSIBLE(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, ULONG Length, BOOLEAN Wait, ULONG LockKey, BOOLEAN CheckForReadOperation, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 40 */
typedef FAST_IO_CHECK_IF_POSSIBLE *PFAST_IO_CHECK_IF_POSSIBLE;

/* 84 */
typedef BOOLEAN __stdcall FAST_IO_READ(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, ULONG Length, BOOLEAN Wait, ULONG LockKey, PVOID Buffer, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 83 */
typedef FAST_IO_READ *PFAST_IO_READ;

/* 86 */
typedef BOOLEAN __stdcall FAST_IO_WRITE(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, ULONG Length, BOOLEAN Wait, ULONG LockKey, PVOID Buffer, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 85 */
typedef FAST_IO_WRITE *PFAST_IO_WRITE;

/* 89 */
typedef struct _FILE_BASIC_INFORMATION *PFILE_BASIC_INFORMATION;

/* 88 */
typedef BOOLEAN __stdcall FAST_IO_QUERY_BASIC_INFO(struct _FILE_OBJECT *FileObject, BOOLEAN Wait, PFILE_BASIC_INFORMATION Buffer, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 87 */
typedef FAST_IO_QUERY_BASIC_INFO *PFAST_IO_QUERY_BASIC_INFO;

/* 93 */
typedef struct _FILE_STANDARD_INFORMATION *PFILE_STANDARD_INFORMATION;

/* 92 */
typedef BOOLEAN __stdcall FAST_IO_QUERY_STANDARD_INFO(struct _FILE_OBJECT *FileObject, BOOLEAN Wait, PFILE_STANDARD_INFORMATION Buffer, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 91 */
typedef FAST_IO_QUERY_STANDARD_INFO *PFAST_IO_QUERY_STANDARD_INFO;

/* 97 */
typedef struct _KPROCESS *PEPROCESS;

/* 96 */
typedef BOOLEAN __stdcall FAST_IO_LOCK(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, PLARGE_INTEGER Length, PEPROCESS ProcessId, ULONG Key, BOOLEAN FailImmediately, BOOLEAN ExclusiveLock, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 95 */
typedef FAST_IO_LOCK *PFAST_IO_LOCK;

/* 99 */
typedef BOOLEAN __stdcall FAST_IO_UNLOCK_SINGLE(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, PLARGE_INTEGER Length, PEPROCESS ProcessId, ULONG Key, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 98 */
typedef FAST_IO_UNLOCK_SINGLE *PFAST_IO_UNLOCK_SINGLE;

/* 101 */
typedef BOOLEAN __stdcall FAST_IO_UNLOCK_ALL(struct _FILE_OBJECT *FileObject, PEPROCESS ProcessId, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 100 */
typedef FAST_IO_UNLOCK_ALL *PFAST_IO_UNLOCK_ALL;

/* 103 */
typedef BOOLEAN __stdcall FAST_IO_UNLOCK_ALL_BY_KEY(struct _FILE_OBJECT *FileObject, PVOID ProcessId, ULONG Key, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 102 */
typedef FAST_IO_UNLOCK_ALL_BY_KEY *PFAST_IO_UNLOCK_ALL_BY_KEY;

/* 105 */
typedef BOOLEAN __stdcall FAST_IO_DEVICE_CONTROL(struct _FILE_OBJECT *FileObject, BOOLEAN Wait, PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, ULONG IoControlCode, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 104 */
typedef FAST_IO_DEVICE_CONTROL *PFAST_IO_DEVICE_CONTROL;

/* 107 */
typedef void __stdcall FAST_IO_ACQUIRE_FILE(struct _FILE_OBJECT *FileObject);

/* 106 */
typedef FAST_IO_ACQUIRE_FILE *PFAST_IO_ACQUIRE_FILE;

/* 109 */
typedef void __stdcall FAST_IO_RELEASE_FILE(struct _FILE_OBJECT *FileObject);

/* 108 */
typedef FAST_IO_RELEASE_FILE *PFAST_IO_RELEASE_FILE;

/* 111 */
typedef void __stdcall FAST_IO_DETACH_DEVICE(struct _DEVICE_OBJECT *SourceDevice, struct _DEVICE_OBJECT *TargetDevice);

/* 110 */
typedef FAST_IO_DETACH_DEVICE *PFAST_IO_DETACH_DEVICE;

/* 113 */
typedef BOOLEAN __stdcall FAST_IO_QUERY_NETWORK_OPEN_INFO(struct _FILE_OBJECT *FileObject, BOOLEAN Wait, struct _FILE_NETWORK_OPEN_INFORMATION *Buffer, struct _IO_STATUS_BLOCK *IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 112 */
typedef FAST_IO_QUERY_NETWORK_OPEN_INFO *PFAST_IO_QUERY_NETWORK_OPEN_INFO;

/* 116 */
typedef NTSTATUS __stdcall FAST_IO_ACQUIRE_FOR_MOD_WRITE(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER EndingOffset, struct _ERESOURCE **ResourceToRelease, struct _DEVICE_OBJECT *DeviceObject);

/* 115 */
typedef FAST_IO_ACQUIRE_FOR_MOD_WRITE *PFAST_IO_ACQUIRE_FOR_MOD_WRITE;

/* 129 */
typedef BOOLEAN __stdcall FAST_IO_MDL_READ(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, ULONG Length, ULONG LockKey, PMDL *MdlChain, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 128 */
typedef FAST_IO_MDL_READ *PFAST_IO_MDL_READ;

/* 133 */
typedef BOOLEAN __stdcall FAST_IO_MDL_READ_COMPLETE(struct _FILE_OBJECT *FileObject, PMDL MdlChain, struct _DEVICE_OBJECT *DeviceObject);

/* 132 */
typedef FAST_IO_MDL_READ_COMPLETE *PFAST_IO_MDL_READ_COMPLETE;

/* 135 */
typedef BOOLEAN __stdcall FAST_IO_PREPARE_MDL_WRITE(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, ULONG Length, ULONG LockKey, PMDL *MdlChain, PIO_STATUS_BLOCK IoStatus, struct _DEVICE_OBJECT *DeviceObject);

/* 134 */
typedef FAST_IO_PREPARE_MDL_WRITE *PFAST_IO_PREPARE_MDL_WRITE;

/* 137 */
typedef BOOLEAN __stdcall FAST_IO_MDL_WRITE_COMPLETE(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, PMDL MdlChain, struct _DEVICE_OBJECT *DeviceObject);

/* 136 */
typedef FAST_IO_MDL_WRITE_COMPLETE *PFAST_IO_MDL_WRITE_COMPLETE;

/* 139 */
typedef BOOLEAN __stdcall FAST_IO_READ_COMPRESSED(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, ULONG Length, ULONG LockKey, PVOID Buffer, PMDL *MdlChain, PIO_STATUS_BLOCK IoStatus, struct _COMPRESSED_DATA_INFO *CompressedDataInfo, ULONG CompressedDataInfoLength, struct _DEVICE_OBJECT *DeviceObject);

/* 138 */
typedef FAST_IO_READ_COMPRESSED *PFAST_IO_READ_COMPRESSED;

/* 142 */
typedef BOOLEAN __stdcall FAST_IO_WRITE_COMPRESSED(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, ULONG Length, ULONG LockKey, PVOID Buffer, PMDL *MdlChain, PIO_STATUS_BLOCK IoStatus, struct _COMPRESSED_DATA_INFO *CompressedDataInfo, ULONG CompressedDataInfoLength, struct _DEVICE_OBJECT *DeviceObject);

/* 141 */
typedef FAST_IO_WRITE_COMPRESSED *PFAST_IO_WRITE_COMPRESSED;

/* 144 */
typedef BOOLEAN __stdcall FAST_IO_MDL_READ_COMPLETE_COMPRESSED(struct _FILE_OBJECT *FileObject, PMDL MdlChain, struct _DEVICE_OBJECT *DeviceObject);

/* 143 */
typedef FAST_IO_MDL_READ_COMPLETE_COMPRESSED *PFAST_IO_MDL_READ_COMPLETE_COMPRESSED;

/* 146 */
typedef BOOLEAN __stdcall FAST_IO_MDL_WRITE_COMPLETE_COMPRESSED(struct _FILE_OBJECT *FileObject, PLARGE_INTEGER FileOffset, PMDL MdlChain, struct _DEVICE_OBJECT *DeviceObject);

/* 145 */
typedef FAST_IO_MDL_WRITE_COMPLETE_COMPRESSED *PFAST_IO_MDL_WRITE_COMPLETE_COMPRESSED;

/* 343 */
typedef struct _FILE_NETWORK_OPEN_INFORMATION *PFILE_NETWORK_OPEN_INFORMATION;

/* 148 */
typedef BOOLEAN __stdcall FAST_IO_QUERY_OPEN(struct _IRP *Irp, PFILE_NETWORK_OPEN_INFORMATION NetworkInformation, struct _DEVICE_OBJECT *DeviceObject);

/* 147 */
typedef FAST_IO_QUERY_OPEN *PFAST_IO_QUERY_OPEN;

/* 345 */
typedef NTSTATUS __stdcall FAST_IO_RELEASE_FOR_MOD_WRITE(struct _FILE_OBJECT *FileObject, struct _ERESOURCE *ResourceToRelease, struct _DEVICE_OBJECT *DeviceObject);

/* 344 */
typedef FAST_IO_RELEASE_FOR_MOD_WRITE *PFAST_IO_RELEASE_FOR_MOD_WRITE;

/* 347 */
typedef NTSTATUS __stdcall FAST_IO_ACQUIRE_FOR_CCFLUSH(struct _FILE_OBJECT *FileObject, struct _DEVICE_OBJECT *DeviceObject);

/* 346 */
typedef FAST_IO_ACQUIRE_FOR_CCFLUSH *PFAST_IO_ACQUIRE_FOR_CCFLUSH;

/* 349 */
typedef NTSTATUS __stdcall FAST_IO_RELEASE_FOR_CCFLUSH(struct _FILE_OBJECT *FileObject, struct _DEVICE_OBJECT *DeviceObject);

/* 348 */
typedef FAST_IO_RELEASE_FOR_CCFLUSH *PFAST_IO_RELEASE_FOR_CCFLUSH;

/* 39 */
struct _FAST_IO_DISPATCH
{
  ULONG SizeOfFastIoDispatch;
  PFAST_IO_CHECK_IF_POSSIBLE FastIoCheckIfPossible;
  PFAST_IO_READ FastIoRead;
  PFAST_IO_WRITE FastIoWrite;
  PFAST_IO_QUERY_BASIC_INFO FastIoQueryBasicInfo;
  PFAST_IO_QUERY_STANDARD_INFO FastIoQueryStandardInfo;
  PFAST_IO_LOCK FastIoLock;
  PFAST_IO_UNLOCK_SINGLE FastIoUnlockSingle;
  PFAST_IO_UNLOCK_ALL FastIoUnlockAll;
  PFAST_IO_UNLOCK_ALL_BY_KEY FastIoUnlockAllByKey;
  PFAST_IO_DEVICE_CONTROL FastIoDeviceControl;
  PFAST_IO_ACQUIRE_FILE AcquireFileForNtCreateSection;
  PFAST_IO_RELEASE_FILE ReleaseFileForNtCreateSection;
  PFAST_IO_DETACH_DEVICE FastIoDetachDevice;
  PFAST_IO_QUERY_NETWORK_OPEN_INFO FastIoQueryNetworkOpenInfo;
  PFAST_IO_ACQUIRE_FOR_MOD_WRITE AcquireForModWrite;
  PFAST_IO_MDL_READ MdlRead;
  PFAST_IO_MDL_READ_COMPLETE MdlReadComplete;
  PFAST_IO_PREPARE_MDL_WRITE PrepareMdlWrite;
  PFAST_IO_MDL_WRITE_COMPLETE MdlWriteComplete;
  PFAST_IO_READ_COMPRESSED FastIoReadCompressed;
  PFAST_IO_WRITE_COMPRESSED FastIoWriteCompressed;
  PFAST_IO_MDL_READ_COMPLETE_COMPRESSED MdlReadCompleteCompressed;
  PFAST_IO_MDL_WRITE_COMPLETE_COMPRESSED MdlWriteCompleteCompressed;
  PFAST_IO_QUERY_OPEN FastIoQueryOpen;
  PFAST_IO_RELEASE_FOR_MOD_WRITE ReleaseForModWrite;
  PFAST_IO_ACQUIRE_FOR_CCFLUSH AcquireForCcFlush;
  PFAST_IO_RELEASE_FOR_CCFLUSH ReleaseForCcFlush;
};

/* 131 */
struct _MDL
{
  struct _MDL *Next;
  CSHORT Size;
  CSHORT MdlFlags;
  struct _EPROCESS *Process;
  PVOID MappedSystemVa;
  PVOID StartVa;
  ULONG ByteCount;
  ULONG ByteOffset;
};

/* 176 */
typedef struct _IO_SECURITY_CONTEXT *PIO_SECURITY_CONTEXT;

/* 175 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$502122D1A42362B108E5158884513E4D
{
  PIO_SECURITY_CONTEXT SecurityContext;
  ULONG Options;
  __declspec(align(8)) USHORT FileAttributes;
  USHORT ShareAccess;
  __declspec(align(8)) ULONG EaLength;
};

/* 200 */
typedef struct _NAMED_PIPE_CREATE_PARAMETERS *PNAMED_PIPE_CREATE_PARAMETERS;

/* 199 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$B6C0E447A90B79AEFA8F9249CE8F183F
{
  PIO_SECURITY_CONTEXT SecurityContext;
  ULONG Options;
  __declspec(align(8)) USHORT Reserved;
  USHORT ShareAccess;
  PNAMED_PIPE_CREATE_PARAMETERS Parameters;
};

/* 203 */
typedef struct _MAILSLOT_CREATE_PARAMETERS *PMAILSLOT_CREATE_PARAMETERS;

/* 202 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$4ECB4BBAC29C474F4B1FDBE6B16B96B3
{
  PIO_SECURITY_CONTEXT SecurityContext;
  ULONG Options;
  __declspec(align(8)) USHORT Reserved;
  USHORT ShareAccess;
  PMAILSLOT_CREATE_PARAMETERS Parameters;
};

/* 205 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$19595C4FDD76DF396DCB47E02D8CE804
{
  ULONG Length;
  __declspec(align(8)) ULONG Key;
  ULONG Flags;
  LARGE_INTEGER ByteOffset;
};

/* 208 */
enum _FILE_INFORMATION_CLASS
{
  FileDirectoryInformation = 0x1,
  FileFullDirectoryInformation = 0x2,
  FileBothDirectoryInformation = 0x3,
  FileBasicInformation = 0x4,
  FileStandardInformation = 0x5,
  FileInternalInformation = 0x6,
  FileEaInformation = 0x7,
  FileAccessInformation = 0x8,
  FileNameInformation = 0x9,
  FileRenameInformation = 0xA,
  FileLinkInformation = 0xB,
  FileNamesInformation = 0xC,
  FileDispositionInformation = 0xD,
  FilePositionInformation = 0xE,
  FileFullEaInformation = 0xF,
  FileModeInformation = 0x10,
  FileAlignmentInformation = 0x11,
  FileAllInformation = 0x12,
  FileAllocationInformation = 0x13,
  FileEndOfFileInformation = 0x14,
  FileAlternateNameInformation = 0x15,
  FileStreamInformation = 0x16,
  FilePipeInformation = 0x17,
  FilePipeLocalInformation = 0x18,
  FilePipeRemoteInformation = 0x19,
  FileMailslotQueryInformation = 0x1A,
  FileMailslotSetInformation = 0x1B,
  FileCompressionInformation = 0x1C,
  FileObjectIdInformation = 0x1D,
  FileCompletionInformation = 0x1E,
  FileMoveClusterInformation = 0x1F,
  FileQuotaInformation = 0x20,
  FileReparsePointInformation = 0x21,
  FileNetworkOpenInformation = 0x22,
  FileAttributeTagInformation = 0x23,
  FileTrackingInformation = 0x24,
  FileIdBothDirectoryInformation = 0x25,
  FileIdFullDirectoryInformation = 0x26,
  FileValidDataLengthInformation = 0x27,
  FileShortNameInformation = 0x28,
  FileIoCompletionNotificationInformation = 0x29,
  FileIoStatusBlockRangeInformation = 0x2A,
  FileIoPriorityHintInformation = 0x2B,
  FileSfioReserveInformation = 0x2C,
  FileSfioVolumeInformation = 0x2D,
  FileHardLinkInformation = 0x2E,
  FileProcessIdsUsingFileInformation = 0x2F,
  FileNormalizedNameInformation = 0x30,
  FileNetworkPhysicalNameInformation = 0x31,
  FileIdGlobalTxDirectoryInformation = 0x32,
  FileIsRemoteDeviceInformation = 0x33,
  FileUnusedInformation = 0x34,
  FileNumaNodeInformation = 0x35,
  FileStandardLinkInformation = 0x36,
  FileRemoteProtocolInformation = 0x37,
  FileMaximumInformation = 0x38,
};

/* 207 */
typedef enum _FILE_INFORMATION_CLASS FILE_INFORMATION_CLASS;

/* 206 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$6A556B20638983A22D68712867326CBB
{
  ULONG Length;
  PUNICODE_STRING FileName;
  FILE_INFORMATION_CLASS FileInformationClass;
  __declspec(align(8)) ULONG FileIndex;
};

/* 209 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$F1FB7B7206FBB228C223D533AFBCB926
{
  ULONG Length;
  __declspec(align(8)) ULONG CompletionFilter;
};

/* 212 */
enum _DIRECTORY_NOTIFY_INFORMATION_CLASS
{
  DirectoryNotifyInformation = 0x1,
  DirectoryNotifyExtendedInformation = 0x2,
};

/* 211 */
typedef enum _DIRECTORY_NOTIFY_INFORMATION_CLASS DIRECTORY_NOTIFY_INFORMATION_CLASS;

/* 210 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$3504904A9B7D3A962144091A63172654
{
  ULONG Length;
  __declspec(align(8)) ULONG CompletionFilter;
  __declspec(align(8)) DIRECTORY_NOTIFY_INFORMATION_CLASS DirectoryNotifyInformationClass;
};

/* 213 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$607E139328A4604A66FA807B5013BC6F
{
  ULONG Length;
  __declspec(align(8)) FILE_INFORMATION_CLASS FileInformationClass;
};

/* 217 */
struct _IO_STACK_LOCATION::$::$::$A1B04431FB6E59C2D561338119C8AE61::$5395532E35CA13A919E63C6E41FE24BB
{
  BOOLEAN ReplaceIfExists;
  BOOLEAN AdvanceOnly;
};

/* 216 */
union _IO_STACK_LOCATION::$::$AB1B8735119157E5D1443CA717CFC90B::$A1B04431FB6E59C2D561338119C8AE61
{
  struct
  {
    BOOLEAN ReplaceIfExists;
    BOOLEAN AdvanceOnly;
  };
  ULONG ClusterCount;
  HANDLE DeleteHandle;
};

/* 214 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$AB1B8735119157E5D1443CA717CFC90B
{
  ULONG Length;
  __declspec(align(8)) FILE_INFORMATION_CLASS FileInformationClass;
  PFILE_OBJECT FileObject;
  union
  {
    struct
    {
      BOOLEAN ReplaceIfExists;
      BOOLEAN AdvanceOnly;
    };
    ULONG ClusterCount;
    HANDLE DeleteHandle;
  };
};

/* 218 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$6D71BC2EE0BEC6E164C292EB723A644F
{
  ULONG Length;
  PVOID EaList;
  ULONG EaListLength;
  __declspec(align(8)) ULONG EaIndex;
};

/* 219 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$AFA69771633799B8FB97339D76F53EAE
{
  ULONG Length;
};

/* 222 */
enum _FSINFOCLASS
{
  FileFsVolumeInformation = 0x1,
  FileFsLabelInformation = 0x2,
  FileFsSizeInformation = 0x3,
  FileFsDeviceInformation = 0x4,
  FileFsAttributeInformation = 0x5,
  FileFsControlInformation = 0x6,
  FileFsFullSizeInformation = 0x7,
  FileFsObjectIdInformation = 0x8,
  FileFsDriverPathInformation = 0x9,
  FileFsMaximumInformation = 0xA,
};

/* 221 */
typedef enum _FSINFOCLASS FS_INFORMATION_CLASS;

/* 220 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$8F4C8BAB08B5A02F6903FB32DA7A20A0
{
  ULONG Length;
  __declspec(align(8)) FS_INFORMATION_CLASS FsInformationClass;
};

/* 223 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$544CD38FB1143AA2EF8E4E19ECBE0BC1
{
  ULONG OutputBufferLength;
  __declspec(align(8)) ULONG InputBufferLength;
  __declspec(align(8)) ULONG FsControlCode;
  PVOID Type3InputBuffer;
};

/* 224 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$BDE1C18626D9C387EACC2762ED2EBE62
{
  PLARGE_INTEGER Length;
  __declspec(align(8)) ULONG Key;
  LARGE_INTEGER ByteOffset;
};

/* 225 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$D5072EFA0FD1785335960F91D4F54465
{
  ULONG OutputBufferLength;
  __declspec(align(8)) ULONG InputBufferLength;
  __declspec(align(8)) ULONG IoControlCode;
  PVOID Type3InputBuffer;
};

/* 227 */
typedef DWORD SECURITY_INFORMATION;

/* 226 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$D83D451722FAB9487C7255AEE094D32E
{
  SECURITY_INFORMATION SecurityInformation;
  __declspec(align(8)) ULONG Length;
};

/* 228 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$E1830675726AC350ADD284B511E01E52
{
  SECURITY_INFORMATION SecurityInformation;
  PSECURITY_DESCRIPTOR SecurityDescriptor;
};

/* 229 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$FA02ECF11A69AC1E6B191DC34CAEB912
{
  PVPB Vpb;
  PDEVICE_OBJECT DeviceObject;
};

/* 230 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$B2B4984C7002DD41520623255E2F9497
{
  struct _SCSI_REQUEST_BLOCK *Srb;
};

/* 234 */
typedef PVOID PSID;

/* 235 */
typedef struct _FILE_GET_QUOTA_INFORMATION *PFILE_GET_QUOTA_INFORMATION;

/* 233 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$525464D5DCAD8B8C6AA0F9E4B917EADA
{
  ULONG Length;
  PSID StartSid;
  PFILE_GET_QUOTA_INFORMATION SidList;
  ULONG SidListLength;
};

/* 244 */
enum _DEVICE_RELATION_TYPE
{
  BusRelations = 0x0,
  EjectionRelations = 0x1,
  PowerRelations = 0x2,
  RemovalRelations = 0x3,
  TargetDeviceRelation = 0x4,
  SingleBusRelations = 0x5,
  TransportRelations = 0x6,
};

/* 243 */
typedef enum _DEVICE_RELATION_TYPE DEVICE_RELATION_TYPE;

/* 242 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$670710264263D47AAED285B3D8DDF250
{
  DEVICE_RELATION_TYPE Type;
};

/* 246 */
typedef struct _INTERFACE *PINTERFACE;

/* 245 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$7995DA36ED0214F9D006DCD5B47162D4
{
  const GUID *InterfaceType;
  USHORT Size;
  USHORT Version;
  PINTERFACE Interface;
  PVOID InterfaceSpecificData;
};

/* 251 */
typedef struct _DEVICE_CAPABILITIES *PDEVICE_CAPABILITIES;

/* 250 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$6B11BC409C8BDB4C1D2CF8E6F83B383D
{
  PDEVICE_CAPABILITIES Capabilities;
};

/* 258 */
typedef struct _IO_RESOURCE_REQUIREMENTS_LIST *PIO_RESOURCE_REQUIREMENTS_LIST;

/* 257 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$E3C1BD80419791D70DF0170630DDCD15
{
  PIO_RESOURCE_REQUIREMENTS_LIST IoResourceRequirementList;
};

/* 284 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$A7E969D4AB37DFCCDF3B9267E9AA5B4E
{
  ULONG WhichSpace;
  PVOID Buffer;
  ULONG Offset;
  __declspec(align(8)) ULONG Length;
};

/* 285 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$CAFA629F92AFE900ACAC7E5B47418F4C
{
  BOOLEAN Lock;
};

/* 288 */
enum $2A8472B1E6C2A8931738C92032F03B5A
{
  BusQueryDeviceID = 0x0,
  BusQueryHardwareIDs = 0x1,
  BusQueryCompatibleIDs = 0x2,
  BusQueryInstanceID = 0x3,
  BusQueryDeviceSerialNumber = 0x4,
  BusQueryContainerID = 0x5,
};

/* 287 */
typedef enum $2A8472B1E6C2A8931738C92032F03B5A BUS_QUERY_ID_TYPE;

/* 286 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$03E399533941020534C84F7B69BA6C0D
{
  BUS_QUERY_ID_TYPE IdType;
};

/* 291 */
enum $CD1AEEBAB641DEC86F01C12702A854EA
{
  DeviceTextDescription = 0x0,
  DeviceTextLocationInformation = 0x1,
};

/* 290 */
typedef enum $CD1AEEBAB641DEC86F01C12702A854EA DEVICE_TEXT_TYPE;

/* 292 */
typedef DWORD LCID;

/* 289 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$B4A62011343B3DB9A4CF5A16B9E2E60D
{
  DEVICE_TEXT_TYPE DeviceTextType;
  __declspec(align(8)) LCID LocaleId;
};

/* 295 */
enum _DEVICE_USAGE_NOTIFICATION_TYPE
{
  DeviceUsageTypeUndefined = 0x0,
  DeviceUsageTypePaging = 0x1,
  DeviceUsageTypeHibernation = 0x2,
  DeviceUsageTypeDumpFile = 0x3,
  DeviceUsageTypeBoot = 0x4,
  DeviceUsageTypePostDisplay = 0x5,
};

/* 294 */
typedef enum _DEVICE_USAGE_NOTIFICATION_TYPE DEVICE_USAGE_NOTIFICATION_TYPE;

/* 293 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$9262F46D7DDB73DE5D2FA4C200481D73
{
  BOOLEAN InPath;
  BOOLEAN Reserved[3];
  __declspec(align(8)) DEVICE_USAGE_NOTIFICATION_TYPE Type;
};

/* 256 */
enum _SYSTEM_POWER_STATE
{
  PowerSystemUnspecified = 0x0,
  PowerSystemWorking = 0x1,
  PowerSystemSleeping1 = 0x2,
  PowerSystemSleeping2 = 0x3,
  PowerSystemSleeping3 = 0x4,
  PowerSystemHibernate = 0x5,
  PowerSystemShutdown = 0x6,
  PowerSystemMaximum = 0x7,
};

/* 255 */
typedef enum _SYSTEM_POWER_STATE SYSTEM_POWER_STATE;

/* 296 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$B225BF4DA8BD0649341E73B822EE9BDC
{
  SYSTEM_POWER_STATE PowerState;
};

/* 298 */
typedef struct _POWER_SEQUENCE *PPOWER_SEQUENCE;

/* 297 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$A3F11F7237E1D19F6A2E9E54FFFFB312
{
  PPOWER_SEQUENCE PowerSequence;
};

/* 305 */
struct _SYSTEM_POWER_STATE_CONTEXT::$24C8B4A8D8171F5B81AB3D9B532BE167::$D446BF98445B25F2A957A6F10A39C71E
{
  unsigned __int32 Reserved1 : 8;
  unsigned __int32 TargetSystemState : 4;
  unsigned __int32 EffectiveSystemState : 4;
  unsigned __int32 CurrentSystemState : 4;
  unsigned __int32 IgnoreHibernationPath : 1;
  unsigned __int32 PseudoTransition : 1;
  unsigned __int32 KernelSoftReboot : 1;
  unsigned __int32 DirectedDripsTransition : 1;
  unsigned __int32 Reserved2 : 8;
};

/* 304 */
union _SYSTEM_POWER_STATE_CONTEXT::$24C8B4A8D8171F5B81AB3D9B532BE167
{
  struct
  {
    unsigned __int32 Reserved1 : 8;
    unsigned __int32 TargetSystemState : 4;
    unsigned __int32 EffectiveSystemState : 4;
    unsigned __int32 CurrentSystemState : 4;
    unsigned __int32 IgnoreHibernationPath : 1;
    unsigned __int32 PseudoTransition : 1;
    unsigned __int32 KernelSoftReboot : 1;
    unsigned __int32 DirectedDripsTransition : 1;
    unsigned __int32 Reserved2 : 8;
  };
  ULONG ContextAsUlong;
};

/* 303 */
struct _SYSTEM_POWER_STATE_CONTEXT
{
  union
  {
    struct
    {
      unsigned __int32 Reserved1 : 8;
      unsigned __int32 TargetSystemState : 4;
      unsigned __int32 EffectiveSystemState : 4;
      unsigned __int32 CurrentSystemState : 4;
      unsigned __int32 IgnoreHibernationPath : 1;
      unsigned __int32 PseudoTransition : 1;
      unsigned __int32 KernelSoftReboot : 1;
      unsigned __int32 DirectedDripsTransition : 1;
      unsigned __int32 Reserved2 : 8;
    };
    ULONG ContextAsUlong;
  };
};

/* 302 */
typedef struct _SYSTEM_POWER_STATE_CONTEXT SYSTEM_POWER_STATE_CONTEXT;

/* 301 */
union _IO_STACK_LOCATION::$::$9010306D1331644169105A79F87BFB5E::$7E80610E1B9C691709D7734F8FEF924B
{
  ULONG SystemContext;
  SYSTEM_POWER_STATE_CONTEXT SystemPowerStateContext;
};

/* 307 */
enum _POWER_STATE_TYPE
{
  SystemPowerState = 0x0,
  DevicePowerState = 0x1,
};

/* 306 */
typedef enum _POWER_STATE_TYPE POWER_STATE_TYPE;

/* 254 */
enum _DEVICE_POWER_STATE
{
  PowerDeviceUnspecified = 0x0,
  PowerDeviceD0 = 0x1,
  PowerDeviceD1 = 0x2,
  PowerDeviceD2 = 0x3,
  PowerDeviceD3 = 0x4,
  PowerDeviceMaximum = 0x5,
};

/* 253 */
typedef enum _DEVICE_POWER_STATE DEVICE_POWER_STATE;

/* 309 */
union _POWER_STATE
{
  SYSTEM_POWER_STATE SystemState;
  DEVICE_POWER_STATE DeviceState;
};

/* 308 */
typedef union _POWER_STATE POWER_STATE;

/* 311 */
enum $0FC989869F227A36D749990E523E5F04
{
  PowerActionNone = 0x0,
  PowerActionReserved = 0x1,
  PowerActionSleep = 0x2,
  PowerActionHibernate = 0x3,
  PowerActionShutdown = 0x4,
  PowerActionShutdownReset = 0x5,
  PowerActionShutdownOff = 0x6,
  PowerActionWarmEject = 0x7,
};

/* 310 */
typedef enum $0FC989869F227A36D749990E523E5F04 POWER_ACTION;

/* 300 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$9010306D1331644169105A79F87BFB5E
{
  union
  {
    ULONG SystemContext;
    SYSTEM_POWER_STATE_CONTEXT SystemPowerStateContext;
  };
  __declspec(align(8)) POWER_STATE_TYPE Type;
  __declspec(align(8)) POWER_STATE State;
  __declspec(align(8)) POWER_ACTION ShutdownType;
};

/* 313 */
typedef struct _CM_RESOURCE_LIST *PCM_RESOURCE_LIST;

/* 312 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$69C11E4E3904219D9A8207E8DBA8FECD
{
  PCM_RESOURCE_LIST AllocatedResources;
  PCM_RESOURCE_LIST AllocatedResourcesTranslated;
};

/* 335 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$D24474CE3B68EBF89E5A61C71CBC75EE
{
  ULONG_PTR ProviderId;
  PVOID DataPath;
  ULONG BufferSize;
  PVOID Buffer;
};

/* 336 */
struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$15881024B0F660B7398AF4B4249A3A24
{
  PVOID Argument1;
  PVOID Argument2;
  PVOID Argument3;
  PVOID Argument4;
};

/* 174 */
union _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF
{
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$502122D1A42362B108E5158884513E4D Create;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$B6C0E447A90B79AEFA8F9249CE8F183F CreatePipe;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$4ECB4BBAC29C474F4B1FDBE6B16B96B3 CreateMailslot;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$19595C4FDD76DF396DCB47E02D8CE804 Read;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$19595C4FDD76DF396DCB47E02D8CE804 Write;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$6A556B20638983A22D68712867326CBB QueryDirectory;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$F1FB7B7206FBB228C223D533AFBCB926 NotifyDirectory;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$3504904A9B7D3A962144091A63172654 NotifyDirectoryEx;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$607E139328A4604A66FA807B5013BC6F QueryFile;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$AB1B8735119157E5D1443CA717CFC90B SetFile;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$6D71BC2EE0BEC6E164C292EB723A644F QueryEa;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$AFA69771633799B8FB97339D76F53EAE SetEa;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$8F4C8BAB08B5A02F6903FB32DA7A20A0 QueryVolume;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$8F4C8BAB08B5A02F6903FB32DA7A20A0 SetVolume;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$544CD38FB1143AA2EF8E4E19ECBE0BC1 FileSystemControl;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$BDE1C18626D9C387EACC2762ED2EBE62 LockControl;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$D5072EFA0FD1785335960F91D4F54465 DeviceIoControl;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$D83D451722FAB9487C7255AEE094D32E QuerySecurity;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$E1830675726AC350ADD284B511E01E52 SetSecurity;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$FA02ECF11A69AC1E6B191DC34CAEB912 MountVolume;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$FA02ECF11A69AC1E6B191DC34CAEB912 VerifyVolume;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$B2B4984C7002DD41520623255E2F9497 Scsi;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$525464D5DCAD8B8C6AA0F9E4B917EADA QueryQuota;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$AFA69771633799B8FB97339D76F53EAE SetQuota;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$670710264263D47AAED285B3D8DDF250 QueryDeviceRelations;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$7995DA36ED0214F9D006DCD5B47162D4 QueryInterface;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$6B11BC409C8BDB4C1D2CF8E6F83B383D DeviceCapabilities;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$E3C1BD80419791D70DF0170630DDCD15 FilterResourceRequirements;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$A7E969D4AB37DFCCDF3B9267E9AA5B4E ReadWriteConfig;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$CAFA629F92AFE900ACAC7E5B47418F4C SetLock;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$03E399533941020534C84F7B69BA6C0D QueryId;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$B4A62011343B3DB9A4CF5A16B9E2E60D QueryDeviceText;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$9262F46D7DDB73DE5D2FA4C200481D73 UsageNotification;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$B225BF4DA8BD0649341E73B822EE9BDC WaitWake;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$A3F11F7237E1D19F6A2E9E54FFFFB312 PowerSequence;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$9010306D1331644169105A79F87BFB5E Power;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$69C11E4E3904219D9A8207E8DBA8FECD StartDevice;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$D24474CE3B68EBF89E5A61C71CBC75EE WMI;
  struct _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF::$15881024B0F660B7398AF4B4249A3A24 Others;
};

/* 340 */
typedef struct _IRP IRP;

/* 339 */
typedef IRP *PIRP;

/* 338 */
typedef NTSTATUS __stdcall IO_COMPLETION_ROUTINE(PDEVICE_OBJECT DeviceObject, PIRP Irp, PVOID Context);

/* 337 */
typedef IO_COMPLETION_ROUTINE *PIO_COMPLETION_ROUTINE;

/* 173 */
struct _IO_STACK_LOCATION
{
  UCHAR MajorFunction;
  UCHAR MinorFunction;
  UCHAR Flags;
  UCHAR Control;
  union _IO_STACK_LOCATION::$3F40624FA6BA75D391A2F4D7FEA8ACCF Parameters;
  PDEVICE_OBJECT DeviceObject;
  PFILE_OBJECT FileObject;
  PIO_COMPLETION_ROUTINE CompletionRoutine;
  PVOID Context;
};

/* 46 */
typedef struct _SECTION_OBJECT_POINTERS SECTION_OBJECT_POINTERS;

/* 45 */
typedef SECTION_OBJECT_POINTERS *PSECTION_OBJECT_POINTERS;

/* 75 */
typedef struct _IO_COMPLETION_CONTEXT *PIO_COMPLETION_CONTEXT;

/* 42 */
struct _FILE_OBJECT
{
  CSHORT Type;
  CSHORT Size;
  PDEVICE_OBJECT DeviceObject;
  PVPB Vpb;
  PVOID FsContext;
  PVOID FsContext2;
  PSECTION_OBJECT_POINTERS SectionObjectPointer;
  PVOID PrivateCacheMap;
  NTSTATUS FinalStatus;
  struct _FILE_OBJECT *RelatedFileObject;
  BOOLEAN LockOperation;
  BOOLEAN DeletePending;
  BOOLEAN ReadAccess;
  BOOLEAN WriteAccess;
  BOOLEAN DeleteAccess;
  BOOLEAN SharedRead;
  BOOLEAN SharedWrite;
  BOOLEAN SharedDelete;
  ULONG Flags;
  UNICODE_STRING FileName;
  LARGE_INTEGER CurrentByteOffset;
  ULONG Waiters;
  ULONG Busy;
  PVOID LastLock;
  KEVENT Lock;
  KEVENT Event;
  PIO_COMPLETION_CONTEXT CompletionContext;
  KSPIN_LOCK IrpListLock;
  LIST_ENTRY IrpList;
  PVOID FileObjectExtension;
};

/* 382 */
struct _DEVICE_OBJECT_POWER_EXTENSION;

/* 90 */
struct _FILE_BASIC_INFORMATION
{
  LARGE_INTEGER CreationTime;
  LARGE_INTEGER LastAccessTime;
  LARGE_INTEGER LastWriteTime;
  LARGE_INTEGER ChangeTime;
  ULONG FileAttributes;
};

/* 94 */
struct _FILE_STANDARD_INFORMATION
{
  LARGE_INTEGER AllocationSize;
  LARGE_INTEGER EndOfFile;
  ULONG NumberOfLinks;
  BOOLEAN DeletePending;
  BOOLEAN Directory;
};

/* 114 */
struct _FILE_NETWORK_OPEN_INFORMATION
{
  LARGE_INTEGER CreationTime;
  LARGE_INTEGER LastAccessTime;
  LARGE_INTEGER LastWriteTime;
  LARGE_INTEGER ChangeTime;
  LARGE_INTEGER AllocationSize;
  LARGE_INTEGER EndOfFile;
  ULONG FileAttributes;
};

/* 118 */
typedef struct _OWNER_ENTRY *POWNER_ENTRY;

/* 123 */
typedef __int16 SHORT;

/* 125 */
struct _ERESOURCE::$0F9CA66D6BD1B66FB152E2AC5421C126::$70F280A3DEE89B0F258B5EC8A3BE63AA
{
  UCHAR ReservedLowFlags;
  UCHAR WaiterPriority;
};

/* 124 */
union _ERESOURCE::$0F9CA66D6BD1B66FB152E2AC5421C126
{
  USHORT Flag;
  struct
  {
    UCHAR ReservedLowFlags;
    UCHAR WaiterPriority;
  };
};

/* 120 */
typedef ULONG_PTR ERESOURCE_THREAD;

/* 122 */
struct _OWNER_ENTRY::$818A6BB8E639852A52D20A2B257A1D60::$E71B718CD8428E7C8AA4A0868051E710
{
  unsigned __int32 IoPriorityBoosted : 1;
  unsigned __int32 OwnerReferenced : 1;
  unsigned __int32 IoQoSPriorityBoosted : 1;
  unsigned __int32 OwnerCount : 29;
};

/* 121 */
union _OWNER_ENTRY::$818A6BB8E639852A52D20A2B257A1D60
{
  struct
  {
    unsigned __int32 IoPriorityBoosted : 1;
    unsigned __int32 OwnerReferenced : 1;
    unsigned __int32 IoQoSPriorityBoosted : 1;
    unsigned __int32 OwnerCount : 29;
  };
  ULONG TableSize;
};

/* 119 */
struct _OWNER_ENTRY
{
  ERESOURCE_THREAD OwnerThread;
  union
  {
    struct
    {
      unsigned __int32 IoPriorityBoosted : 1;
      unsigned __int32 OwnerReferenced : 1;
      unsigned __int32 IoQoSPriorityBoosted : 1;
      unsigned __int32 OwnerCount : 29;
    };
    ULONG TableSize;
  };
};

/* 126 */
typedef struct _OWNER_ENTRY OWNER_ENTRY;

/* 127 */
union _ERESOURCE::$6485B31835FF66149107F3D6F17C6B98
{
  PVOID Address;
  ULONG_PTR CreatorBackTraceIndex;
};

/* 117 */
struct _ERESOURCE
{
  LIST_ENTRY SystemResourcesList;
  POWNER_ENTRY OwnerTable;
  SHORT ActiveCount;
  union
  {
    USHORT Flag;
    struct
    {
      UCHAR ReservedLowFlags;
      UCHAR WaiterPriority;
    };
  };
  PVOID SharedWaiters;
  PVOID ExclusiveWaiters;
  OWNER_ENTRY OwnerEntry;
  ULONG ActiveEntries;
  ULONG ContentionCount;
  ULONG NumberOfSharedWaiters;
  ULONG NumberOfExclusiveWaiters;
  PVOID Reserved2;
  union
  {
    PVOID Address;
    ULONG_PTR CreatorBackTraceIndex;
  };
  KSPIN_LOCK SpinLock;
};

/* 140 */
struct _COMPRESSED_DATA_INFO
{
  USHORT CompressionFormatAndEngine;
  UCHAR CompressionUnitShift;
  UCHAR ChunkShift;
  UCHAR ClusterShift;
  UCHAR Reserved;
  USHORT NumberOfChunks;
  ULONG CompressedChunkSizes[1];
};

/* 178 */
typedef struct _SECURITY_QUALITY_OF_SERVICE *PSECURITY_QUALITY_OF_SERVICE;

/* 183 */
typedef struct _ACCESS_STATE *PACCESS_STATE;

/* 187 */
typedef DWORD ACCESS_MASK;

/* 177 */
struct _IO_SECURITY_CONTEXT
{
  PSECURITY_QUALITY_OF_SERVICE SecurityQos;
  PACCESS_STATE AccessState;
  ACCESS_MASK DesiredAccess;
  ULONG FullCreateOptions;
};

/* 201 */
struct _NAMED_PIPE_CREATE_PARAMETERS
{
  ULONG NamedPipeType;
  ULONG ReadMode;
  ULONG CompletionMode;
  ULONG MaximumInstances;
  ULONG InboundQuota;
  ULONG OutboundQuota;
  LARGE_INTEGER DefaultTimeout;
  BOOLEAN TimeoutSpecified;
};

/* 204 */
struct _MAILSLOT_CREATE_PARAMETERS
{
  ULONG MailslotQuota;
  ULONG MaximumMessageSize;
  LARGE_INTEGER ReadTimeout;
  BOOLEAN TimeoutSpecified;
};

/* 232 */
union _SCSI_REQUEST_BLOCK::$881DB7056EA58ED002ED8DEAE86A2418
{
  ULONG InternalStatus;
  ULONG QueueSortKey;
  ULONG LinkTimeoutValue;
};

/* 231 */
struct _SCSI_REQUEST_BLOCK
{
  USHORT Length;
  UCHAR Function;
  UCHAR SrbStatus;
  UCHAR ScsiStatus;
  UCHAR PathId;
  UCHAR TargetId;
  UCHAR Lun;
  UCHAR QueueTag;
  UCHAR QueueAction;
  UCHAR CdbLength;
  UCHAR SenseInfoBufferLength;
  ULONG SrbFlags;
  ULONG DataTransferLength;
  ULONG TimeOutValue;
  PVOID DataBuffer;
  PVOID SenseInfoBuffer;
  struct _SCSI_REQUEST_BLOCK *NextSrb;
  PVOID OriginalRequest;
  PVOID SrbExtension;
  union
  {
    ULONG InternalStatus;
    ULONG QueueSortKey;
    ULONG LinkTimeoutValue;
  };
  ULONG Reserved;
  UCHAR Cdb[16];
};

/* 239 */
typedef unsigned __int8 BYTE;

/* 241 */
struct _SID_IDENTIFIER_AUTHORITY
{
  BYTE Value[6];
};

/* 240 */
typedef struct _SID_IDENTIFIER_AUTHORITY SID_IDENTIFIER_AUTHORITY;

/* 238 */
struct _SID
{
  BYTE Revision;
  BYTE SubAuthorityCount;
  SID_IDENTIFIER_AUTHORITY IdentifierAuthority;
  DWORD SubAuthority[1];
};

/* 237 */
typedef struct _SID SID;

/* 236 */
struct _FILE_GET_QUOTA_INFORMATION
{
  ULONG NextEntryOffset;
  ULONG SidLength;
  SID Sid;
};

/* 248 */
typedef void (__stdcall *PINTERFACE_REFERENCE)(PVOID Context);

/* 249 */
typedef void (__stdcall *PINTERFACE_DEREFERENCE)(PVOID Context);

/* 247 */
struct _INTERFACE
{
  USHORT Size;
  USHORT Version;
  PVOID Context;
  PINTERFACE_REFERENCE InterfaceReference;
  PINTERFACE_DEREFERENCE InterfaceDereference;
};

/* 252 */
struct _DEVICE_CAPABILITIES
{
  USHORT Size;
  USHORT Version;
  unsigned __int32 DeviceD1 : 1;
  unsigned __int32 DeviceD2 : 1;
  unsigned __int32 LockSupported : 1;
  unsigned __int32 EjectSupported : 1;
  unsigned __int32 Removable : 1;
  unsigned __int32 DockDevice : 1;
  unsigned __int32 UniqueID : 1;
  unsigned __int32 SilentInstall : 1;
  unsigned __int32 RawDeviceOK : 1;
  unsigned __int32 SurpriseRemovalOK : 1;
  unsigned __int32 WakeFromD0 : 1;
  unsigned __int32 WakeFromD1 : 1;
  unsigned __int32 WakeFromD2 : 1;
  unsigned __int32 WakeFromD3 : 1;
  unsigned __int32 HardwareDisabled : 1;
  unsigned __int32 NonDynamic : 1;
  unsigned __int32 WarmEjectSupported : 1;
  unsigned __int32 NoDisplayInUI : 1;
  unsigned __int32 Reserved1 : 1;
  unsigned __int32 WakeFromInterrupt : 1;
  unsigned __int32 SecureDevice : 1;
  unsigned __int32 ChildOfVgaEnabledBridge : 1;
  unsigned __int32 DecodeIoOnBoot : 1;
  unsigned __int32 Reserved : 9;
  ULONG Address;
  ULONG UINumber;
  DEVICE_POWER_STATE DeviceState[7];
  SYSTEM_POWER_STATE SystemWake;
  DEVICE_POWER_STATE DeviceWake;
  ULONG D1Latency;
  ULONG D2Latency;
  ULONG D3Latency;
};

/* 261 */
enum _INTERFACE_TYPE
{
  InterfaceTypeUndefined = 0xFFFFFFFF,
  Internal = 0x0,
  Isa = 0x1,
  Eisa = 0x2,
  MicroChannel = 0x3,
  TurboChannel = 0x4,
  PCIBus = 0x5,
  VMEBus = 0x6,
  NuBus = 0x7,
  PCMCIABus = 0x8,
  CBus = 0x9,
  MPIBus = 0xA,
  MPSABus = 0xB,
  ProcessorInternal = 0xC,
  InternalPowerBus = 0xD,
  PNPISABus = 0xE,
  PNPBus = 0xF,
  MaximumInterfaceType = 0x10,
};

/* 260 */
typedef enum _INTERFACE_TYPE INTERFACE_TYPE;

/* 268 */
typedef LARGE_INTEGER PHYSICAL_ADDRESS;

/* 267 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$6F2DCCC140478981F4C84F12EF58F0E8
{
  ULONG Length;
  ULONG Alignment;
  PHYSICAL_ADDRESS MinimumAddress;
  PHYSICAL_ADDRESS MaximumAddress;
};

/* 271 */
enum _IRQ_DEVICE_POLICY
{
  IrqPolicyMachineDefault = 0x0,
  IrqPolicyAllCloseProcessors = 0x1,
  IrqPolicyOneCloseProcessor = 0x2,
  IrqPolicyAllProcessorsInMachine = 0x3,
  IrqPolicySpecifiedProcessors = 0x4,
  IrqPolicySpreadMessagesAcrossAllProcessors = 0x5,
  IrqPolicyAllProcessorsInMachineWhenSteered = 0x6,
};

/* 270 */
typedef enum _IRQ_DEVICE_POLICY IRQ_DEVICE_POLICY;

/* 273 */
enum _IRQ_PRIORITY
{
  IrqPriorityUndefined = 0x0,
  IrqPriorityLow = 0x1,
  IrqPriorityNormal = 0x2,
  IrqPriorityHigh = 0x3,
};

/* 272 */
typedef enum _IRQ_PRIORITY IRQ_PRIORITY;

/* 269 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$A5682085F38B4530410BC09C233C00C6
{
  ULONG MinimumVector;
  ULONG MaximumVector;
  IRQ_DEVICE_POLICY AffinityPolicy;
  IRQ_PRIORITY PriorityPolicy;
  KAFFINITY TargetedProcessors;
};

/* 275 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$17B187B8C3CC0C2C04D148A62457C1B5
{
  ULONG MinimumChannel;
  ULONG MaximumChannel;
};

/* 276 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$711A32C7DEC837C87D3D622B5D6CA547
{
  ULONG RequestLine;
  ULONG Reserved;
  ULONG Channel;
  ULONG TransferWidth;
};

/* 277 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$812F79A5FC2BE6FE62CE9F41854F4845
{
  ULONG Data[3];
};

/* 278 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$CFEA0CDFCF8B31E537C8D44F49AF209A
{
  ULONG Length;
  ULONG MinBusNumber;
  ULONG MaxBusNumber;
  ULONG Reserved;
};

/* 279 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$F28011FF41998B198A306197E74BFABD
{
  ULONG Priority;
  ULONG Reserved1;
  ULONG Reserved2;
};

/* 280 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$90A8EEE83C9F91E29DD5F8EE42946559
{
  ULONG Length40;
  ULONG Alignment40;
  PHYSICAL_ADDRESS MinimumAddress;
  PHYSICAL_ADDRESS MaximumAddress;
};

/* 281 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$9B5808D9D572DC66358F5E90A8A74F4F
{
  ULONG Length48;
  ULONG Alignment48;
  PHYSICAL_ADDRESS MinimumAddress;
  PHYSICAL_ADDRESS MaximumAddress;
};

/* 282 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$DA030873C766E4C7B95104F99E17565C
{
  ULONG Length64;
  ULONG Alignment64;
  PHYSICAL_ADDRESS MinimumAddress;
  PHYSICAL_ADDRESS MaximumAddress;
};

/* 283 */
struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$ACFC0B8B00258A4187B421B4FDF1B18A
{
  UCHAR Class;
  UCHAR Type;
  UCHAR Reserved1;
  UCHAR Reserved2;
  ULONG IdLowPart;
  ULONG IdHighPart;
};

/* 266 */
union _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02
{
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$6F2DCCC140478981F4C84F12EF58F0E8 Port;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$6F2DCCC140478981F4C84F12EF58F0E8 Memory;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$A5682085F38B4530410BC09C233C00C6 Interrupt;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$17B187B8C3CC0C2C04D148A62457C1B5 Dma;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$711A32C7DEC837C87D3D622B5D6CA547 DmaV3;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$6F2DCCC140478981F4C84F12EF58F0E8 Generic;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$812F79A5FC2BE6FE62CE9F41854F4845 DevicePrivate;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$CFEA0CDFCF8B31E537C8D44F49AF209A BusNumber;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$F28011FF41998B198A306197E74BFABD ConfigData;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$90A8EEE83C9F91E29DD5F8EE42946559 Memory40;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$9B5808D9D572DC66358F5E90A8A74F4F Memory48;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$DA030873C766E4C7B95104F99E17565C Memory64;
  struct _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02::$ACFC0B8B00258A4187B421B4FDF1B18A Connection;
};

/* 265 */
struct _IO_RESOURCE_DESCRIPTOR
{
  UCHAR Option;
  UCHAR Type;
  UCHAR ShareDisposition;
  UCHAR Spare1;
  USHORT Flags;
  USHORT Spare2;
  union _IO_RESOURCE_DESCRIPTOR::$E0BCE46F03EEBF143E8289580A8E6C02 u;
};

/* 264 */
typedef struct _IO_RESOURCE_DESCRIPTOR IO_RESOURCE_DESCRIPTOR;

/* 263 */
struct _IO_RESOURCE_LIST
{
  USHORT Version;
  USHORT Revision;
  ULONG Count;
  IO_RESOURCE_DESCRIPTOR Descriptors[1];
};

/* 262 */
typedef struct _IO_RESOURCE_LIST IO_RESOURCE_LIST;

/* 259 */
struct _IO_RESOURCE_REQUIREMENTS_LIST
{
  ULONG ListSize;
  INTERFACE_TYPE InterfaceType;
  ULONG BusNumber;
  ULONG SlotNumber;
  ULONG Reserved[3];
  ULONG AlternativeLists;
  IO_RESOURCE_LIST List[1];
};

/* 299 */
struct _POWER_SEQUENCE
{
  ULONG SequenceD1;
  ULONG SequenceD2;
  ULONG SequenceD3;
};

/* 322 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$BBBCA153A119060DF311607C16E36BB2
{
  PHYSICAL_ADDRESS Start;
  ULONG Length;
};
#pragma pack(pop)

/* 323 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$BB7094CF39B58C60385FAAA7DFEE1197
{
  ULONG Level;
  ULONG Vector;
  KAFFINITY Affinity;
};
#pragma pack(pop)

/* 326 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$::$::$DE3CCB929DB832FEAC38EBA7195AFD95::$D155ACCA6E988C466DB4311FB52073D0
{
  USHORT Reserved;
  USHORT MessageCount;
  ULONG Vector;
  KAFFINITY Affinity;
};
#pragma pack(pop)

/* 327 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$::$::$DE3CCB929DB832FEAC38EBA7195AFD95::$BB7094CF39B58C60385FAAA7DFEE1197
{
  ULONG Level;
  ULONG Vector;
  KAFFINITY Affinity;
};
#pragma pack(pop)

/* 325 */
#pragma pack(push, 1)
union _CM_PARTIAL_RESOURCE_DESCRIPTOR::$::$4320D89A9BBD0A464899BC45363B6444::$DE3CCB929DB832FEAC38EBA7195AFD95
{
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$::$::$DE3CCB929DB832FEAC38EBA7195AFD95::$D155ACCA6E988C466DB4311FB52073D0 Raw;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$::$::$DE3CCB929DB832FEAC38EBA7195AFD95::$BB7094CF39B58C60385FAAA7DFEE1197 Translated;
};
#pragma pack(pop)

/* 324 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$4320D89A9BBD0A464899BC45363B6444
{
  #pragma pack(push, 1)
  union
  {
    struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$::$::$DE3CCB929DB832FEAC38EBA7195AFD95::$D155ACCA6E988C466DB4311FB52073D0 Raw;
    struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$::$::$DE3CCB929DB832FEAC38EBA7195AFD95::$BB7094CF39B58C60385FAAA7DFEE1197 Translated;
  };
  #pragma pack(pop)
};
#pragma pack(pop)

/* 328 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$1F3D6AF14FC8FA95287DDF447D6BE47F
{
  ULONG Channel;
  ULONG Port;
  ULONG Reserved1;
};
#pragma pack(pop)

/* 329 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$812F79A5FC2BE6FE62CE9F41854F4845
{
  ULONG Data[3];
};
#pragma pack(pop)

/* 330 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$D2EE30319AFD96435F4334D8E12C7935
{
  ULONG Start;
  ULONG Length;
  ULONG Reserved;
};
#pragma pack(pop)

/* 331 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$6BF00F84A5C727E3B25245E9FBDFB278
{
  ULONG DataSize;
  ULONG Reserved1;
  ULONG Reserved2;
};
#pragma pack(pop)

/* 332 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$EB36DC85652755C8EC8C69A205B736DB
{
  PHYSICAL_ADDRESS Start;
  ULONG Length40;
};
#pragma pack(pop)

/* 333 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$08205AB7C2167E8C9C2BF0274334A928
{
  PHYSICAL_ADDRESS Start;
  ULONG Length48;
};
#pragma pack(pop)

/* 334 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$05881B79B3CAFBFC2EAF6FE4C8FAB51F
{
  PHYSICAL_ADDRESS Start;
  ULONG Length64;
};
#pragma pack(pop)

/* 321 */
#pragma pack(push, 1)
union _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F
{
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$BBBCA153A119060DF311607C16E36BB2 Generic;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$BBBCA153A119060DF311607C16E36BB2 Port;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$BB7094CF39B58C60385FAAA7DFEE1197 Interrupt;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$4320D89A9BBD0A464899BC45363B6444 MessageInterrupt;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$BBBCA153A119060DF311607C16E36BB2 Memory;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$1F3D6AF14FC8FA95287DDF447D6BE47F Dma;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$812F79A5FC2BE6FE62CE9F41854F4845 DevicePrivate;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$D2EE30319AFD96435F4334D8E12C7935 BusNumber;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$6BF00F84A5C727E3B25245E9FBDFB278 DeviceSpecificData;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$EB36DC85652755C8EC8C69A205B736DB Memory40;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$08205AB7C2167E8C9C2BF0274334A928 Memory48;
  struct _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F::$05881B79B3CAFBFC2EAF6FE4C8FAB51F Memory64;
};
#pragma pack(pop)

/* 320 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_DESCRIPTOR
{
  UCHAR Type;
  UCHAR ShareDisposition;
  USHORT Flags;
  union _CM_PARTIAL_RESOURCE_DESCRIPTOR::$ADB721E5076B7192632491DCDDDBEB4F u;
};
#pragma pack(pop)

/* 319 */
typedef struct _CM_PARTIAL_RESOURCE_DESCRIPTOR CM_PARTIAL_RESOURCE_DESCRIPTOR;

/* 318 */
#pragma pack(push, 1)
struct _CM_PARTIAL_RESOURCE_LIST
{
  USHORT Version;
  USHORT Revision;
  ULONG Count;
  CM_PARTIAL_RESOURCE_DESCRIPTOR PartialDescriptors[1];
};
#pragma pack(pop)

/* 317 */
typedef struct _CM_PARTIAL_RESOURCE_LIST CM_PARTIAL_RESOURCE_LIST;

/* 316 */
#pragma pack(push, 1)
struct _CM_FULL_RESOURCE_DESCRIPTOR
{
  INTERFACE_TYPE InterfaceType;
  ULONG BusNumber;
  CM_PARTIAL_RESOURCE_LIST PartialResourceList;
};
#pragma pack(pop)

/* 315 */
typedef struct _CM_FULL_RESOURCE_DESCRIPTOR CM_FULL_RESOURCE_DESCRIPTOR;

/* 314 */
#pragma pack(push, 1)
struct _CM_RESOURCE_LIST
{
  ULONG Count;
  CM_FULL_RESOURCE_DESCRIPTOR List[1];
};
#pragma pack(pop)

/* 47 */
struct _SECTION_OBJECT_POINTERS
{
  PVOID DataSectionObject;
  PVOID SharedCacheMap;
  PVOID ImageSectionObject;
};

/* 76 */
struct _IO_COMPLETION_CONTEXT
{
  PVOID Port;
  PVOID Key;
};

/* 181 */
enum _SECURITY_IMPERSONATION_LEVEL
{
  SecurityAnonymous = 0x0,
  SecurityIdentification = 0x1,
  SecurityImpersonation = 0x2,
  SecurityDelegation = 0x3,
};

/* 180 */
typedef enum _SECURITY_IMPERSONATION_LEVEL SECURITY_IMPERSONATION_LEVEL;

/* 182 */
typedef BOOLEAN SECURITY_CONTEXT_TRACKING_MODE;

/* 179 */
struct _SECURITY_QUALITY_OF_SERVICE
{
  DWORD Length;
  SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
  SECURITY_CONTEXT_TRACKING_MODE ContextTrackingMode;
  BOOLEAN EffectiveOnly;
};

/* 186 */
struct _LUID
{
  DWORD LowPart;
  LONG HighPart;
};

/* 185 */
typedef struct _LUID LUID;

/* 190 */
typedef PVOID PACCESS_TOKEN;

/* 189 */
struct _SECURITY_SUBJECT_CONTEXT
{
  PACCESS_TOKEN ClientToken;
  SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
  PACCESS_TOKEN PrimaryToken;
  PVOID ProcessAuditId;
};

/* 188 */
typedef struct _SECURITY_SUBJECT_CONTEXT SECURITY_SUBJECT_CONTEXT;

/* 196 */
#pragma pack(push, 4)
struct _LUID_AND_ATTRIBUTES
{
  LUID Luid;
  DWORD Attributes;
};
#pragma pack(pop)

/* 195 */
typedef struct _LUID_AND_ATTRIBUTES LUID_AND_ATTRIBUTES;

/* 194 */
struct _INITIAL_PRIVILEGE_SET
{
  ULONG PrivilegeCount;
  ULONG Control;
  LUID_AND_ATTRIBUTES Privilege[3];
};

/* 193 */
typedef struct _INITIAL_PRIVILEGE_SET INITIAL_PRIVILEGE_SET;

/* 198 */
struct _PRIVILEGE_SET
{
  DWORD PrivilegeCount;
  DWORD Control;
  LUID_AND_ATTRIBUTES Privilege[1];
};

/* 197 */
typedef struct _PRIVILEGE_SET PRIVILEGE_SET;

/* 192 */
union _ACCESS_STATE::$18D81C5C1A882E7A2AF410C6CD9261CD
{
  INITIAL_PRIVILEGE_SET InitialPrivilegeSet;
  PRIVILEGE_SET PrivilegeSet;
};

/* 184 */
struct _ACCESS_STATE
{
  LUID OperationID;
  BOOLEAN SecurityEvaluated;
  BOOLEAN GenerateAudit;
  BOOLEAN GenerateOnClose;
  BOOLEAN PrivilegesAllocated;
  ULONG Flags;
  ACCESS_MASK RemainingDesiredAccess;
  ACCESS_MASK PreviouslyGrantedAccess;
  ACCESS_MASK OriginalDesiredAccess;
  SECURITY_SUBJECT_CONTEXT SubjectSecurityContext;
  PSECURITY_DESCRIPTOR SecurityDescriptor;
  PVOID AuxData;
  union _ACCESS_STATE::$18D81C5C1A882E7A2AF410C6CD9261CD Privileges;
  BOOLEAN AuditPrivileges;
  UNICODE_STRING ObjectName;
  UNICODE_STRING ObjectTypeName;
};

/* 383 */
union __declspec(align(64)) __m512
{
  float m512_f32[16];
};

/* 384 */
union __declspec(align(64)) __m512d
{
  double m512d_f64[8];
};

/* 385 */
union __declspec(align(64)) __m512i
{
  __int8 m512i_i8[64];
  __int16 m512i_i16[32];
  __int32 m512i_i32[16];
  __int64 m512i_i64[8];
  unsigned __int8 m512i_u8[64];
  unsigned __int16 m512i_u16[32];
  unsigned __int32 m512i_u32[16];
  unsigned __int64 m512i_u64[8];
};

/* 386 */
union __declspec(align(16)) __m128
{
  float m128_f32[4];
  unsigned __int64 m128_u64[2];
  __int8 m128_i8[16];
  __int16 m128_i16[8];
  __int32 m128_i32[4];
  __int64 m128_i64[2];
  unsigned __int8 m128_u8[16];
  unsigned __int16 m128_u16[8];
  unsigned __int32 m128_u32[4];
};

